# Generated by Django 4.0.3 on 2022-06-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0017_remove_emprestimos_nome_emprestado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 9, 54, 57, 800589)),
        ),
    ]
